// Headshot portrait pixel maps — 32×32 square, transparent background.
// Extracted from reference images via Python.
Object.assign(palette, {
  a: "#020202",
  b: "#12110E",
  c: "#DAAC78",
  d: "#C69D70",
  e: "#FCFCFD",
  f: "#272623",
  g: "#949494",
  h: "#D55C92",
  i: "#CB4784",
  j: "#B26C71",
  k: "#E3C86A",
  l: "#F2EEEB",
  m: "#E4B887",
  n: "#481C57",
  o: "#792871",
  p: "#A82C83",
  q: "#688D44",
  r: "#557939",
  s: "#C3BB70",
  t: "#37322D",
  u: "#D49739",
  v: "#CCCACB",
  x: "#eb3131",
});

// ─── Plain (slate-blue bg) ────────────────────────────────
const hsPlain = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............aaaaa.............",
  "............aabaabbaa...........",
  "...........abbbabbbbba..........",
  "...........bbbababaaba..........",
  "..........abbabccccbcca.........",
  "..........ababbccccccca.........",
  "..........bbbbcccccccca.........",
  ".........abaaacccccccca.........",
  ".........aacaacbbbccbba.........",
  ".........acccccccdcccda.........",
  ".........accccccaacccaa.........",
  ".........aadaccccccccca.........",
  "........aaalaccccccacca.........",
  "........aaagadcccccaaca.........",
  "........aaaaaccccccccca.........",
  "........aabbaaccccbbbca.........",
  ".......aaabbaacccccccca.........",
  ".......afaabbadccccccca.........",
  ".......affaaaacdcccccaa.........",
  ".......affffaaccaaaaaafa........",
  ".......aaffffaccccaffffa........",
  ".......aaaffaaccccaffaaa........",
  "......aafaaffaccccaffaafa.......",
  "......afffabffacccaffaffa.......",
  "......affffbabfacafaafffa.......",
];

// ─── Bubblegum (gold bg) ──────────────────────────────────
const hsBubblegum = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............aaaaa.............",
  "............aabaabbaa...........",
  "...........abbbabbbbba..........",
  "...........bbbababaaba..........",
  "..........abbabccccbcca.........",
  "..........ababbccccccca.........",
  "..........bbbbcccccccca.........",
  ".........abaaacccccccca.........",
  ".........aacaacbbbccbba.........",
  ".........accccccdcccdca.........",
  ".........accccccacccaca.........",
  ".........aadacccacccaca.........",
  "........aaalaccccccccca.........",
  "........aaagadcccccacca.........",
  "........aaaaaccccccccahaa.......",
  "........aabbaaccccbbahhhha......",
  ".......aaabbaaccccccbhhhha......",
  ".......afaabbadcccccaiihh.......",
  ".......affaaaacdcccccaaia.......",
  ".......affffaaccaaaaaafa........",
  ".......aaffffaccccaffffa........",
  ".......aaaffaaccccaffaaa........",
  "......aafaaffaccccaffaafa.......",
  "......afffabffacccaffaffa.......",
  "......affffbabfacafaafffa.......",
];

// ─── Black Cat (brown bg) ─────────────────────────────────
const hsCat = [
  "................................",
  "................................",
  "................................",
  ".............a......a............",
  "............aja....aja...........",
  "............ajaaaaajja...........",
  "............affffffffa...........",
  "............bfffkffkfff..........",
  "............ffffkffkffa..........",
  "...........afffffffffba..........",
  "...........aafbbfbfbbaa..........",
  "..........abbabccccbcca.........",
  "..........ababbccccccca.........",
  "..........bbbbcccccccca.........",
  ".........abaaacccccccca.........",
  ".........aacaacbbbccbba.........",
  ".........acccccccdcccda.........",
  ".........accccccaacccaa.........",
  ".........aadaccccccccca.........",
  "........aaalaccccccacca.........",
  "........aaagadcccccaaca.........",
  "........aaaaaccccccccca.........",
  "........aabbaaccccbbbca.........",
  ".......aaabbaacccccccca.........",
  ".......afaabbadccccccca.........",
  ".......affaaaacdcccccaa.........",
  ".......affffaaccaaaaaafa........",
  ".......aaffffaccccaffffa........",
  ".......aaaffaaccccaffaaa........",
  "......aafaaffaccccaffaafa.......",
  "......afffabffacccaffaffa.......",
  "......affffbabfacafaafffa.......",
];

// ─── Sunglasses (mauve bg) ────────────────────────────────
const hsSunglasses = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "............aaaaaaaa............",
  "...........aaaffafaaa...........",
  "..........affffffffffa..........",
  ".........affafaaffffaa..........",
  ".........aafccmffccmfaa.........",
  "........aaaammmmmmmmffa.........",
  "........aaammmmmmmmmmfa.........",
  "........aafcmmmmmmmmmaa.........",
  "........aaammmmmmmmmmaa.........",
  "........aaaaaaaaaaaaaaa.........",
  "........aaannnnnnnnnnna.........",
  "........adaoooooooooooa.........",
  "........addapppaaapppaa.........",
  "........alaaaaaccaaaaaa.........",
  "........agammmmmmmmmmaa.........",
  "........aaammmmaammmmaa.........",
  "........aaammmmmmmmmmaa.........",
  "........aaacmmaaaammmaa.........",
  "........aaadmmccccmmmaa.........",
  "........afaacmmmmmmmafa.........",
  "........affacdmmmmmaafa.........",
  ".......aaffamdaaaaaaffa.........",
  ".......afaaamcmmmaafaaa........",
  ".........faamcmmma..aa..........",
  "...........ammmmma..............",
  "...........ammmmma..............",
  "...........acmmmca..............",
];

// ─── T-Rex (slate-blue bg) ────────────────────────────────
const hsTrex = [
  "................................",
  ".................aaa............",
  "................aqqqaa..........",
  "................rqqxqqa.........",
  "..............aarqqqqqa.........",
  "...........aaarqqrqba...........",
  "...........aqqqrqsaqqa..........",
  "............aqqqasa.............",
  "...........aaaqqaqa.............",
  "..........abbaraaraaa...........",
  ".........aabaaaaaaaaa...........",
  ".........abbbababababa..........",
  "........abbbabccccbcca..........",
  "........abbabcccccccca..........",
  "........aabbacccccccca..........",
  "........abaaacccccccca..........",
  "........aacaacbbbccbba..........",
  "........acccccccdcccda..........",
  "........accccccaacccaa..........",
  "........aadaccccccccca..........",
  ".......aaalaccccccacca..........",
  ".......aaagadcccccaaca..........",
  ".......aaaaaccccccccca..........",
  "........babacccccbbbca..........",
  ".......aabaadcccccccca..........",
  "........abbacdccccccca..........",
  ".......aaabaccdcccccaa..........",
  "......aaabaacccaaaaaa...........",
  "........aaaaccccaa..............",
  ".........a.acccca...............",
  "...........acccca...............",
  "...........acccca...............",
];

// ─── Penguin (mauve bg) ────────────────────────────────────
const hsPenguin = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".............aaaaaa.............",
  "............aatatataa...........",
  "...........abbbtbatbba..........",
  "..........abbbbtbbbtfa..........",
  "..........aabatabbftbaa.........",
  "..........batcccbcccaba.........",
  "..........aacccccccccba.........",
  "..........aacccccccccaa.........",
  "..........abcccccccacba.........",
  ".........aabcaaaccaaaaaa........",
  ".........acaccaccccacaca........",
  ".........addccaccccaccda........",
  ".........addcccccccccdda........",
  ".........alacccccccccala........",
  ".......aaagaccccaacccaga........",
  "......afffaacccccccccaa.........",
  "......afufaadccccccccaa.........",
  "......fvvvaaaccbfbfccaa.........",
  ".....aflllaaaccccccccba.........",
  ".....aflllaaadccccccaaa.........",
  "......allaabacdccccaaaa.........",
  ".......aaafaaccaaaaaabbb........",
  ".......aaaffacccccaffaaa........",
  "......aafaaffaccccaffaaba.......",
  "......afffabffacccaffaffa.......",
  "......affffbabfacafaafffa.......",
];

const headshots = [
  { name: "Plain", map: hsPlain },
  { name: "Penguin", map: hsPenguin },
  { name: "T-Rex", map: hsTrex },
  { name: "Sunglasses", map: hsSunglasses },
  { name: "Black Cat", map: hsCat },
  { name: "Bubblegum", map: hsBubblegum },
];
