// Headshot portrait pixel maps — 32×32 square, transparent background.
// Extracted from reference images via Python.
Object.assign(palette, {
  a: "#DDB369", // portrait bg colour (transparent as '.' in its own portrait)
  b: "#030102",
  c: "#181510",
  d: "#342007",
  e: "#B69560",
  f: "#7F6542", // portrait bg colour (transparent as '.' in its own portrait)
  g: "#543F24",
  h: "#DCC4AC",
  i: "#9C9C9C",
  j: "#D26791",
  k: "#EDB2D0",
  l: "#AF4576",
  m: "#DA4886",
  n: "#893660",
  o: "#B66971",
  p: "#F1DA72",
  q: "#D3D1D2",
  r: "#5F7583", // portrait bg colour (transparent as '.' in its own portrait)
  s: "#D0B192",
  t: "#3F4140",
  u: "#515B65",
  v: "#4D1B58",
  w: "#832E83",
  x: "#A12D82",
  y: "#F5F0EC",
  z: "#9C8163",
  A: "#638E3F",
  B: "#527734",
  C: "#8A6E7C", // portrait bg colour (transparent as '.' in its own portrait)
  D: "#6F5B66",
  E: "#B65E3A",
  F: "#C0BEBF",
});

// ─── Plain (slate-blue bg) ────────────────────────────────
const hsPlain = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".............cbbbbb.............",
  "............bbcccccb............",
  "...........bcccbccccb...........",
  "...........cccbcbcbbcb..........",
  "..........bccbhaaaaaaab.........",
  "..........bcccaaaaaaaab.........",
  ".........bcccbaaaaaaaab.........",
  ".........bbcbbaaaaaaaab.........",
  ".........bcbbcaeccaabbb.........",
  ".........bbabbaaaaaaaab.........",
  ".........bfaaaaabeaafgb.........",
  ".........bfeaaaaeaaaaab.........",
  ".........bbqsaaaaaaaaab.........",
  ".........bciteaaaaabaab.........",
  ".........bcbbeaaaaaaaab.........",
  "........bbcbbeaaaahssab.........",
  ".......ccbccbsaaaaeeeab.........",
  ".......cccbcbsaaaaaaaab.........",
  ".......bccbbbsaaaaaaabc.........",
  ".......bcccbbaaaabbbbcbt........",
  ".......bcccccaaaacccbcct........",
  ".......tbccccbaaacccccbu........",
  ".......bcbbcccbeacccbbcb........",
  "......bccccbbcccbccbccccb.......",
  "......bcccccccbcccccccccb.......",
  "......bcccccccbcccbcccccb.......",
];

// ─── Bubblegum (gold bg) ────────────────────────────────
const hsBubblegum = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".............bbbbbb.............",
  "............bcbcbccb............",
  "...........bcccbccccb...........",
  "..........bccbccbccbcb..........",
  ".........cccccc....c.cb.........",
  ".........bccbd........b.........",
  ".........bcbc.........b.........",
  ".........cbcb.........b.........",
  "........ebbbc..eee..eeb.........",
  "........fbb.b..eee..eeb.........",
  "........gb......be..bcb.........",
  "........db......b...b.b.........",
  "........gbbh..........b.........",
  "........gcbib......d..b.........",
  "........fcbbb........cjjd.......",
  "........bcbcbe......bjjkjb......",
  ".......dbcccb.....ccljjjjb......",
  ".......bcccbb.......cmmjjb......",
  "......gccbbcb........bnnf.......",
  "......bccbcbb....eefdbce........",
  "......bcccccb....bbcbcce........",
  ".......bcccccb...bccccce........",
  "......bbccccccb..bcccccb........",
  ".....cbbcbbccccb.bccbbcb........",
  ".....bbccccbbbccbccbccccb.......",
  ".....cbcccccccbcccbcccccb.......",
  ".....cbcccccccbcccbcccccb.......",
];

// ─── Black Cat (brown bg) ────────────────────────────────
const hsCat = [
  "................................",
  "................................",
  ".........bcb......bb............",
  ".........bocb....bbb............",
  ".........boobbbbbcob............",
  "..........bccccccccb............",
  ".........ccc.bpccbpcb...........",
  ".........bccgbcocbecb...........",
  ".........bccccccccccb...........",
  "..........bcccbcbccb............",
  ".........bcbbbcbcbbcb...........",
  "........gbbbccaaahbabb..........",
  "........bccbbaaaaaaaab..........",
  "........bcbchaaaaaaaab..........",
  "........bbccaaaaaaaaab..........",
  "........bccbaaaaaaaaab..........",
  "........bbabaabbbaabbb..........",
  "........bae.aaabeaabcb..........",
  "........baaaaaabaaabab..........",
  "........bbeaaaaaaaaaab..........",
  "........cbqbaaaaaa.aab..........",
  "........cbbbaaaaaaaaab..........",
  ".......bbbcbeaaaaaaaab..........",
  ".......bbccbaaaahccaab..........",
  "......bcbcbbaaaaaaaaab..........",
  ".....cccbbcbaaaaaaaab...........",
  ".....bccccbbaaaa..gcbcg.........",
  ".....bcccccbaaaabccbcc..........",
  "......bbccccbaaabbcccc..........",
  ".....bbccccccbaabccbbbb.........",
  ".....bbcbbbbccbabccbbcb.........",
  ".....bcccccccbcccccccccb........",
];

// ─── Sunglasses (mauve bg) ────────────────────────────────
const hsSunglasses = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............bbbbbbbb..........",
  ".............bbdgdbddbb.........",
  "............bddbdbbbdbbb........",
  "...........bdbddbdddbddbb.......",
  "...........bddgfdbbfggdbb.......",
  "..........bddssssssssssbbb......",
  "..........bbssssssssssssbb......",
  "..........bdssssssssssssbb......",
  "..........bbssssssssssssbb......",
  "..........bbssssssssssssbb......",
  "..........bbbbbbbbbbbbbbbb......",
  ".........bsbvvvvvvvvvvvvbsb.....",
  ".........bebnnnnnnnnnnwnbeb.....",
  ".........beebxxxbbbcxxxbeeb.....",
  ".........bybsbbbbssebbbzby......",
  ".........gibsssssssaaaasbi......",
  ".........tbbsassaddsasaabb......",
  ".........tbbaasssaaaaaaabb......",
  "........igbbeasasaasaaaabb......",
  "........igbbeasagdddsasabb......",
  "........itbbbsaaaaaaasabbb......",
  "........itbbdbeaaaaasabbbb......",
  ".........bbddbaeaassabbbbb......",
  ".......tbbbbbbssbbbbbbbbbbb.....",
  ".......dbbbbbbaaaaafb.bbdb......",
  "................................",
];

// ─── T-Rex (slate-blue bg) ────────────────────────────────
const hsTrex = [
  "................................",
  ".................bbbt...........",
  "................bAAAtb..........",
  "................BAiAABb.........",
  "...........t..ccBAAccbc.........",
  "...........tbbAAABAdy...........",
  "...........bAAAtAabAAt..........",
  "...........bBAAAAsb.............",
  "...........tbbAcftb.............",
  "..........bbbBAbbBBbb...........",
  ".........bbbbbbbcbbcb...........",
  ".........bbbbbbbcbbcbb..........",
  "........ccbcbdeaaadsab..........",
  "........bbbbbaaaaaaaab..........",
  "........bbcbbaaaaaaaab..........",
  "........bbbbbaaaaaaaab..........",
  "........bbabbadbdaabbb..........",
  "........baaasaadeaaadb..........",
  "........baeaaaabaaaabd..........",
  "........bbeaaaaaaaaaag..........",
  "........bbybeaaaaaasaf..........",
  "........cbbbeaaaaafzaf..........",
  "........cbbbeaaaaaaaae..........",
  "........cbbbaaaaadddaa..........",
  "........bcbbaaaaaaaaae..........",
  "........bccbaaaaaaaaaeu.........",
  "........cbdbaaaaaaaaab..........",
  "......bbbbbbaaaabbbbb...........",
  "........bbtbaaaab...............",
  "...........baaaab...............",
  "...........baaaab...............",
  "...........baaaab...............",
];

// ─── Penguin (mauve bg) ────────────────────────────────
const hsPenguin = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "............tbtbtbtbu...........",
  "...........bcccccbtccb..........",
  "..........bcctctccccccc.........",
  "..........bccctcccttcbb.........",
  "..........bccaaaaaaaacbD........",
  "..........bbaaaaaaaaazbD........",
  "..........bcaaaaaaaaaebu........",
  "..........bcaaaaaaaaahbt........",
  "..........bcabbbaabbbabc........",
  ".........babaazaaaazeaeeD.......",
  ".........beeaabaaaabaaezD.......",
  ".........beeaaaaaaaaaaezu.......",
  ".........Dbbaaaaaaaaaabq........",
  "......bccbubaaaaccaaaabt........",
  "......bcaEubeaaaaaaaaabt........",
  "......tFqbubeaagcccaaabt........",
  ".....bcqqFDbeaaaaaaaahct........",
  ".....btqqyucbeaaaaaaabcc........",
  ".....DbqqFbcbaeaaaaabccc........",
  ".......cbEcbbaabbbbbbcccb.......",
  ".......bbcccbaaaaabcccbb........",
  "......bccbcccbhaaabcccccb.......",
  "......bcccccbcccactcbcccb.......",
  "......bccccccbccbtcbcctcb.......",
  "................................",
  "................................",
];

const headshots = [
  { name: "Plain",      map: hsPlain },
  { name: "Penguin",    map: hsPenguin },
  { name: "T-Rex",      map: hsTrex },
  { name: "Sunglasses", map: hsSunglasses },
  { name: "Black Cat",  map: hsCat },
  { name: "Bubblegum",  map: hsBubblegum },
];