// Headshot portrait pixel maps — 32×32 square, transparent background.
// Extracted from reference images via Python.
Object.assign(palette, {
  a: "#010404",
  b: "#171715",
  c: "#DDAE79",
  d: "#C49C71",
  e: "#ECEBEA",
  f: "#272623",
  g: "#949494",
  h: "#D55C92",
  i: "#CA4784",
  j: "#B16A70",
  k: "#E3C96A",
  l: "#37332D",
  m: "#481C55",
  n: "#7A2872",
  o: "#912B82",
  p: "#6D687E",
  q: "#749D48",
  r: "#628A43",
  s: "#4D7336",
  t: "#C3BA70",
  u: "#3B5928",
  v: "#D5C58B",
  w: "#A7A7A6",
  x: "#D49839",
  y: "#D9D7D5",
  z: "#CA572D",
});

// ─── Plain (slate-blue bg) ────────────────────────────────
const hsPlain = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".............aaaaaa.............",
  "............abbaabbaa...........",
  "...........abbbabbbbba..........",
  "..........abbbababaaba..........",
  "..........abbbbccccccca.........",
  "..........ababcccccccca.........",
  ".........aabbacccccccca.........",
  ".........aabaacccccccca.........",
  ".........abaabcbbaccaaa.........",
  ".........aacaacccccccca.........",
  ".........aadccccadccaaa.........",
  ".........aadcccccccccca.........",
  ".........aaeeccccccccca.........",
  ".........abaadcccccacca.........",
  ".........abaadcccccccca.........",
  "........aabbaacccccccca.........",
  ".......ababbaccccccccca.........",
  ".......abbabaccccccccca.........",
  ".......abbaaaacccccccaa.........",
  ".......abbbaaacccaaaaaa.........",
  ".......abbbbbacccaababba........",
  ".......aabbbbbaccaabbbaa........",
  "......aabaabbbbacabbbbaa........",
  "......aabbbaabbbaabbbbbba.......",
  "......abbbbbbbbbbbbbbbbba.......",
  "................................",
];

// ─── Bubblegum (gold bg) ──────────────────────────────────
const hsBubblegum = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".............aaaaaa.............",
  "............abafabba............",
  "...........bbbbafbbba...........",
  "..........abbabbabbaba..........",
  ".........abbbbbccccbcaa.........",
  ".........abbbbcccccccca.........",
  ".........abbbccccccccca.........",
  ".........aabaccccccccca.........",
  ".........aaaaccbbcccaaa.........",
  "........aaacacccbccccaa.........",
  "........aaccacccacccaaa.........",
  "........aaccccccacccaca.........",
  "........aaaccccccccccca.........",
  "........abagaccccccacca.........",
  "........abaaaccccccccahaa.......",
  "........ababadccccccahhhha......",
  ".......aabbbacccccbbbhhhha......",
  ".......abbbaacccccccaiihh.......",
  ".......bbaaaaccccccccaiia.......",
  "......abbbaaaccccaaaaaaa........",
  "......abbbbbaccccaaaabba........",
  ".......abbbbbacccabbbbaa........",
  "......aabbbbbbaccabbbbba........",
  "......aabbabbbbacabbabbba.......",
  ".....aabbbbaabbbabfabbbba.......",
  ".....aabbbbbbbabbbabbbbba.......",
];

// ─── Black Cat (brown bg) ─────────────────────────────────
const hsCat = [
  "................................",
  "................................",
  ".........aaa......aaa...........",
  ".........ajba....abja...........",
  "..........ajaaaaabbaa...........",
  "..........affffffffa............",
  "..........affaaffakfa...........",
  ".........afffabffakfa...........",
  "..........bffbffbfbfa...........",
  "..........abbbabbbba............",
  ".........abbaabababba...........",
  ".........abaabccccbcaa..........",
  "........abbabcccccccca..........",
  "........ababbcccccccca..........",
  "........aabbacccccccca..........",
  "........abbabcccccccca..........",
  "........aacaaccbbccaaa..........",
  "........addacccaccccda..........",
  "........addccccacccaaa..........",
  "........aadcccccccccca..........",
  "........aaeaccccccacca..........",
  "........aaaaccccccccca..........",
  ".......aabbadcccccccca..........",
  ".......aabbacccccbbbca..........",
  "......ababbaccccccccca..........",
  "......bbbabaccccccccaa..........",
  ".....abbbaaacccccaaaaba.........",
  ".....abbbbbaccccaabaaba.........",
  "......aabbfbacccabfbfba.........",
  ".....aababfbbaccabbbbaaa........",
  ".....abbbabbbbaaafbbabba........",
  "................................",
];

// ─── Sunglasses (mauve bg) ────────────────────────────────
const hsSunglasses = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "..............aaaaaaaa..........",
  ".............aaallaalaa.........",
  "............abbalbbabbba........",
  "...........abbllbbbbblbba.......",
  "...........abbalabbcllbaa.......",
  "..........abalcccccccccbba......",
  "..........aabccccccccccbba......",
  "..........aaccccccccccccba......",
  "..........aaccccccccccccaa......",
  "..........aaaccccccccccaaa......",
  "..........aaaaaaaaaaaaaaaa......",
  ".........acammmmmmmmmmmmaca.....",
  ".........adannoonnnnnnonada.....",
  ".........addaoooaaaaoooadda.....",
  ".........aeaaaaaaccaaaaaae......",
  "..........gaccccccacccccag......",
  "..........aacccccaacccccaa......",
  ".........aaaccccccccccccaa......",
  "........gaaadcccccccccccaa......",
  "........gpaadcccbbbbccccaa......",
  "........gaabaccccccccccaba......",
  "........gaabbadcccccccaaba......",
  ".........abbbacdcccccaabba......",
  "........abbabaccaaaaaaababa.....",
  "................................",
  "................................",
];

// ─── T-Rex (slate-blue bg) ────────────────────────────────
const hsTrex = [
  "................................",
  ".................aaaa...........",
  "................aqarraa.........",
  "...............asrqrrra.........",
  "...........a..assrraaa..........",
  "...........aaarrrsraaa..........",
  "...........asrrrrtaaaa..........",
  "............aurrava.............",
  "...........aaaraaua.............",
  "..........abbasaasaaa...........",
  ".........abbaaaabaafa...........",
  ".........abbaabafaaaba..........",
  "........abbabbccccccca..........",
  "........ababbcccccccca..........",
  "........aabbacccccccca..........",
  "........aaaabccccccccaa.........",
  "........aacaaccbbccaaa..........",
  "........addccccadcccaa..........",
  "........addccccaccccaaa.........",
  ".......aaaeccccccccccaa.........",
  ".......aaawadcccccaacaa.........",
  ".......aaaaadccccccccaa.........",
  ".......aaaaadccccccccaa.........",
  "........fabacccccbfbcca.........",
  "........abaacccccccccaa.........",
  "........abbaccdccccccaa.........",
  ".......aaabaccccccccaa..........",
  "......aaabaaccccaaaaa...........",
  "........aaaaccccaa..............",
  ".........a.acccca...............",
  "...........acccca...............",
  "................................",
];

// ─── Penguin (mauve bg) ────────────────────────────────────
const hsPenguin = [
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  "................................",
  ".............aaaaaaa............",
  "...........aaaalbalbba..........",
  "..........abbablbbblbaa.........",
  "..........aabalabbllbaa.........",
  "..........albccccccccbaa........",
  "..........aacccccccccbaa........",
  "..........abcccccccccbaa........",
  "..........aacccccccccaaa........",
  "..........abcaaaccaaacaa........",
  ".........acaccccccccccac........",
  ".........addccaccccaccdaa.......",
  ".........addccccccccccdd........",
  "..........aacccccccccca.........",
  ".......aaaaaccccaacccca.........",
  "......alxaaadcccccccccaa........",
  "......alyaaadccbbbbcccaa........",
  ".....abeeyaadccccccccaaa........",
  ".....aleeeaaadcccccccaba........",
  "......aeeaaaaadcccccaaaaa.......",
  ".......aazbaaacaaaaaaaaba.......",
  ".......aaabbaaccccabbaaa........",
  "......ablbabbaccccabbaaba.......",
  "......abbblbabbacaababbba.......",
  "................................",
  "................................",
  "................................",
];

const headshots = [
  { name: "Plain",      map: hsPlain },
  { name: "Penguin",    map: hsPenguin },
  { name: "T-Rex",      map: hsTrex },
  { name: "Sunglasses", map: hsSunglasses },
  { name: "Black Cat",  map: hsCat },
  { name: "Bubblegum",  map: hsBubblegum },
];
